version: "3"

services:
  app:
    build: .
    command: npm start
    container_name: app
    ports:
      - "3000:3000"
    #  volumes:
    #  - .:/usr/app
    depends_on:
      - db

  db:
    image: mongo
    container_name: mongo
    volumes:
      - /data:/data/db
    ports:
      - "27017:27017"
    